import LocalizedStrings from 'react-native-localization';
let Strings = new LocalizedStrings({
  en:{
	selectyourlanguage:'Please select your language',
	changepassword:'Change Password',
	mytransactions:'My Transactions',
	moneytransferaccount:'Money Transfer Accounts',
	withdrawrequests:'Withdraw Requests',
	submit:'Submit',
	startdate:'Start Date',
	enddate:'End Date',
	selectdate:'select date',
	save:'Save',
	name:'Name',
	address:'Address',
	city:'City',
	state:'State',
	country:'Country',
	choosecountry:'Choose Country',
	zipcode:'Zip Code',
	fax:'Fax',
	phone:'Phone',
	mobile:'Mobile',
	email:'Email',
	male:'Male',
	female:'Female',
	chooseyourgender:'Choose your gender:',
	update:'Update',
	passwordchangedsuccessfully:'Your password has been changed successfully',
	currentpassword:'Current Password',
	newpassword:'New Password',
	repassword:'Re-type New Password',
	personalinfo:'Personal Info',
	firstname:'First Name',
	enteryourfirstname:'Enter your first name',
	lastname:'Last Name',
	enteryourlastname:'Enter your last name',
	aboutme:'About Me',
	socialinfo:'Social Info',
	website:'Website',
	accountdetails:'Account Details',
	enteraccountdetails:'Enter Account Details',
	amountaddedtowallet:'Amount added to wallet',
	all:'All',
	today:'Today',
	thisweek:'This Week',
	thismonth:'This Month',
	description:'Description',
	credit:'Credit',
	debit:'Debit',
	edit:'Edit',
	next:'NEXT',
	day:'Day',
	hour:'Hour',
	accept:'Accept',
	reject:'Reject',
	activities:'Activities',
	host:'HOST',
	from:'From',
	to:'To',
	bookedon:'Booked On',
	gross:'Gross',
	paymentpending:'Payment Pending',
	waitingforacceptance:'Waiting For Acceptance',
	confirmed:'Confirmed',
	cancelled:'Cancelled',
	rejected:'Rejected',
	expired:'Expired',
	review:'Review',
	dispute:'Dispute',
	attended:'Attended',
	waitingforreview:'Waiting for Review',
	waitingforbookerreview:'Waiting for Booker Review',
	waitingforpaymentcleared:'Waiting for Payment Cleared',
	completed:'Completed',
	enteryouremail:'Enter your email',
	entervalidemail:'Enter valid email',
	enteryourpassword:'Enter your password',
	enterlogincredentials:'Enter your login credentials',
	minlenghtpwd: 'Password should be minimum 6 characters',
	enternewpassword:'Enter new password',
	login:'Login',
	createnewaccount:'Create new account',
	forgotpassword:'Forgot Password',
	sociallogin:'SOCIAL LOGIN',
	loginwithfacebook:'Login with Facebook',
	loginwithtwitter:'Login with Twitter',
	loginwithgoogle:'Login with Google',
	enteryourusername:'Enter your username',
	confirmyourpassword:'Confirm your password',
	acceptterms:'Accept terms and conditions',
	passphrase:'Please enter the email address associated to your account, and we\'ll send you instructions.',
	addresspickmessage:'Please select a address',
	startdatemessage:'Pickup Date should be greater than current date & time',
	enddatemessage:'End Date Should be Greater than Start date & time',
	discount:'Discount',
	offer:'offer',
	nodata:'No data found',
	selectall:'Select All',
	loading:'Loading...',
	specifications:'Specifications',
	feedbacks:'Feedbacks',
	feedback:'Feedback',
	accessories:'Accessories',
	perrental:'per rental',
	insurance:'Insurance',
	taxes:'Taxes,',
	error:'Internal error has occured. Please check with log',
	checklogindetails:'Check your login credentials',
	passwordmismatch:'Password and Confirm password must be same',
	minlengthusername:'Username should be minimum 3 characters',
	minlengthpassword:'Password and Confirm password should be minimum 6 characters',
	preferenceairconditioning:'Air Conditioning',
	preferencenonairconditioning:'Non - Air Conditioning',
	preferencemanualtransmission:'Manual Transmission',
	preferenceautotransmission:'Automatic Transmission',
	preferenceairbag:'Air Bag',
	entervalidurl:'Please check URLs are valid',
	enterhostname:'Enter host name of minimum 2 chars',
	entervalidmobilenumber:'Enter valid mobile number',
	entercurrentpassword:'Enter your current password',
	paynow:'Pay Now',
	rating:'Rating',
	privatenote:'Private Note',
	areyousurewanttodelete:'Are you sure want to delete this from list?',
	enteraccountdetails:'Enter account details',
	cancel:'Cancel',
	nobookings:'No Bookings',
	addtowallet: 'Add To Wallet',
	minwalletamount:'Minimum Wallet Amount: $10.00',
	maxwalletamount:'Maximum wallet amount: $1,000.00',
	minwwithdrawamount:'Minimum withdraw amount: $2.00',
	maxwithdrawamount:'Maximum withdraw amount: $1,000.00',
	minvalue:'Min: ',
	maxvalue:'Max: ',
	payerdetails:'PAYER DETAILS',
	creditcarddetails:'CREDIT CARD DETAILS',
	cardnumber:'Card Number',
	mm:'MM',
	yyyy:'YYYY',
	month:'Month',
	year:'Year',
	nameoncard:'Name on card',
	cardcode:'Card Code',
	availablebalance:'Available Balance',
	entervalidamount:'Enter valid amount',
	checkavailablebalanceandentervalidamount:'Check available balance and enter valid amount',
	enteraddress:'Enter address',
	entercity:'Enter city',
	enterstate:'Enter state',
	enterzipcode:'Enter Zip code',
	entervalidphonenumber:'Enter valid phone number',
	entervalidcardnumber:'Enter valid card number',
	entervalidmonth:'Enter valid month',
	entervalidyear:'Enter valid year',
	enternameoncard:'Enter name on card',
	entervalidcardcode:'Enter valid card code',
	termsofservice:'By clicking the Pay Now button, you agree to these Terms of Service.',
	choosemoneytransferoption:'Choose your money transfer option',
	amount:'Amount',
	date:'Date',
	account:'Account',
	status:'Status',
	cashwithdrawrequests:'CASH WITHDRAW REQUESTS',
	view:'View',
	wallet:'Wallet',
	listingfee:'Listing fee to be paid: $',
	faredetails:'Fare Details',
	details:'Details',
	days:'Day(s)',
	hours:'Hour(s)',
	total:'Total',
	tax:'Tax',
	deposit:'Deposit',
	surchargeamount:'Surcharge Amount',
	totalprice:'Total Price',
	typediscountamount:'Type Discount Amount',
	discount:'Discount',
	insuranceamount:'Insurance Amount',
	walletsuccess:'Your amount has been added to wallet successfully',
	vehiclessuccess:'Your listing fee payment is completed successfully',
	cancelmessage:'Your have cancelled the payment',
	errormessage:'Request could not be processed. Try again later',
	unabletoprocess:'Unable to process your request. Please try again later.',
	walletmessage:'Your balance is not sufficient to pay',
	ordersuccess:'Your order payment has been completed successfully',
	enterprivatenote:'Enter private note',
	provideyourrating:'Select your rating star',
	checkin:'Check In',
	checkout:'Check Out',
	areyousurewanttocheckout:"Are you sure want to check out?",
	cannotreview:'You cannot review when dispute is open',
	coupons:'Coupons',
	couponcode:'Coupon Code',
	entercouponcode:'Enter coupon code',
	apply:'Apply',
	orderamount: 'Order Amount ', 
	myprofile:'MY PROFILE',
	becomeahost:'BECOME A HOST',
	settings:'SETTINGS',
	bookings:'BOOKINGS',
	orders:'ORDERS',
	calendar:'CALENDAR',
	login:'LOGIN',
	logout:'LOGOUT',
	register:'REGISTER',
	inbox:'INBOX',
	sent:'SENT',
	starred:'STARRED',
	signupheader:'SIGN UP',
	acceptterms:'Please accept the terms and conditions',
  }
});
module.exports = Strings;
